In [1]:
import numpy as np
import sys
if "../" not in sys.path:
    sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [2]:
env = GridworldEnv()

In [3]:
def policy_eval(policy, env, Value, discount_factor=1.0):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
            env.nS is a number of states in the environment. 
            env.nA is a number of actions in the environment.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: Gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    for s in range(env.nS):
        v = 0
        for a, a_prob in enumerate(policy[s]):
            for prob, next_state, reward, done in env.P[s][a]:
                v += a_prob * (reward + discount_factor * prob * Value[next_state])

        # delta = max(delta, abs(s - V[s]))
        Value[s] = v
        
    return np.array(Value)

In [4]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
Value = np.zeros(env.nS)

In [5]:
for k in range(11):
    Value = policy_eval(random_policy, env, Value)
    print("k = {}".format(k))
    print(Value.reshape(env.shape))
    print("")

k = 0
[[ 0.        -1.        -1.25      -1.3125   ]
 [-1.        -1.5       -1.6875    -1.75     ]
 [-1.25      -1.6875    -1.84375   -1.8984375]
 [-1.3125    -1.75      -1.8984375  0.       ]]

k = 1
[[ 0.         -1.9375     -2.546875   -2.73046875]
 [-1.9375     -2.8125     -3.23828125 -3.40429688]
 [-2.546875   -3.23828125 -3.56835938 -3.21777344]
 [-2.73046875 -3.40429688 -3.21777344  0.        ]]

k = 2
[[ 0.         -2.82421875 -3.83496094 -4.17504883]
 [-2.82421875 -4.03125    -4.7097168  -4.87670898]
 [-3.83496094 -4.7097168  -4.96374512 -4.26455688]
 [-4.17504883 -4.87670898 -4.26455688  0.        ]]

k = 3
[[ 0.         -3.67260742 -5.0980835  -5.58122253]
 [-3.67260742 -5.19116211 -6.03242493 -6.18872833]
 [-5.0980835  -6.03242493 -6.14849091 -5.15044403]
 [-5.58122253 -6.18872833 -5.15044403  0.        ]]

k = 4
[[ 0.         -4.49046326 -6.30054855 -6.91293049]
 [-4.49046326 -6.26144409 -7.22480297 -7.36922646]
 [-6.30054855 -7.22480297 -7.1876235  -5.9268235 ]
 [-6.9129